name: code_climate_checker

on:
    - push


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                pip install poetry
                make install
            - uses: paambaati/codeclimate-action@v8.0.0
              env:
                CC_TEST_REPORTER_ID: 36090696cba1dca77d8be697eca077d5c337dcca0fbbe6489fae7dca9b776466
              with:
                coverageCommand: make test
                debug: true